version: "3.9"

services:
  frontend:
    image: manishkumar55/todo-app-web:latest
    container_name: turbo-frontend
    ports:
      - "80:3000"             
    environment:
      NODE_ENV: production
    depends_on:
      - backend
      - ws-backend

  backend:
    image: manishkumar55/todo-app-backend:latest
    container_name: turbo-backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  ws-backend:
    image: manishkumar55/todo-app-ws:latest
    container_name: turbo-ws-backend
    ports:
      - "8081:8081"
    env_file:
      - .env
